name: Build asciinema-edit for Windows

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    env:
      GOPATH: C:\dev\tmp
      GOCACHE: C:\dev\tmp\gocache
      GOENV: C:\dev\tmp\goenv
      GOMODCACHE: C:\dev\tmp\gomodcache

    steps:
      - name: Checkout this repo (for workflow file)
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Clone asciinema-edit
        run: git clone https://github.com/cirocosta/asciinema-edit.git

      - name: Build Windows Executable
        run: |
          cd asciinema-edit
          go build -o asciinema-edit.exe

      - name: Upload Windows Executable
        uses: actions/upload-artifact@v4
        with:
          name: asciinema-edit-windows
          path: asciinema-edit/asciinema-edit.exe
