name: Build oqs-provider v0.7.0

on:
  workflow_dispatch: # Allows you to manually trigger the workflow
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout oqs-provider v0.7.0
        uses: actions/checkout@v4
        with:
          repository: open-quantum-safe/oqs-provider
          ref: v0.7.0

      - name: Set up dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential libssl-dev

      - name: Set up dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install cmake openssl

      - name: Set up dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y

      - name: Configure (Linux/macOS)
        if: runner.os == 'Linux' || runner.os == 'macOS'
        run: |
          mkdir build
          cd build
          cmake ..

      - name: Configure (Windows)
        if: runner.os == 'Windows'
        run: |
          mkdir build
          cd build
          cmake .. -G "Visual Studio 17 2022" -A x64

      - name: Build (Linux/macOS)
        if: runner.os == 'Linux' || runner.os == 'macOS'
        run: |
          cd build
          make -j$(nproc)

      - name: Build (Windows)
        if: runner.os == 'Windows'
        run: |
          cd build
          cmake --build . --config Release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: oqs-provider-binaries-${{ matrix.os }}
          path: |
            build/
