name: OpenSSL 3.5.0 Multi-Platform Build

on:
  workflow_dispatch:
  push:
  #   branches: [ main ]

permissions:
  contents: read

jobs:
  build-windows:
    runs-on: windows-2022
    strategy:
      matrix:
        arch: [win64, win32]
    steps:
      - uses: actions/checkout@v4
      - name: Download and Setup OpenSSL Source
        shell: cmd
        run: |
          echo Downloading OpenSSL 3.5.0...
          curl -L -o openssl.zip https://github.com/openssl/openssl/archive/refs/tags/openssl-3.5.0.zip
          echo Extracting archive...
          tar -xf openssl.zip
          echo Renaming directory...
          ren openssl-openssl-3.5.0 openssl
          echo Verifying directory exists...
          dir openssl
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
      - uses: ilammy/setup-nasm@v1
        with:
          platform: ${{ matrix.arch }}
      - name: Setup Perl
        shell: cmd
        run: choco install strawberryperl -y
      - name: Configure
        shell: cmd
        run: |
          cd openssl
          if "${{ matrix.arch }}"=="win64" (
            perl Configure VC-WIN64A no-shared no-module --prefix=C:\OpenSSL --openssldir=C:\OpenSSL\ssl
          ) else (
            perl Configure VC-WIN32 no-shared no-module --prefix=C:\OpenSSL --openssldir=C:\OpenSSL\ssl
          )
      - name: Build
        shell: cmd
        run: |
          cd openssl
          nmake
      - name: Install
        shell: cmd
        run: |
          cd openssl
          nmake install
      - name: Create portable executable
        shell: cmd
        run: |
          echo Creating portable OpenSSL executable...
          copy C:\OpenSSL\bin\openssl.exe openssl.exe
          echo Testing portable executable...
          openssl.exe version
          mkdir portable-package
          copy openssl.exe portable-package\
          echo OpenSSL 3.5.0 Portable - %{{ matrix.arch }}% > portable-package\README.txt
          echo ======================================= >> portable-package\README.txt
          echo. >> portable-package\README.txt
          echo This is a standalone portable version of OpenSSL 3.5.0 >> portable-package\README.txt
          echo No installation required - just run the executable. >> portable-package\README.txt
          echo. >> portable-package\README.txt
          echo Usage: openssl.exe [command] [options] >> portable-package\README.txt
          echo. >> portable-package\README.txt
          echo Examples: >> portable-package\README.txt
          echo   openssl.exe version >> portable-package\README.txt
          echo   openssl.exe list -digest-algorithms >> portable-package\README.txt
          echo   openssl.exe genrsa -out private.key 2048 >> portable-package\README.txt
          echo   openssl.exe req -new -x509 -key private.key -out cert.pem -days 365 >> portable-package\README.txt
          echo. >> portable-package\README.txt
          echo Platform: Windows ${{ matrix.arch }} >> portable-package\README.txt
          echo Version: OpenSSL 3.5.0 >> portable-package\README.txt
      - name: Package binaries
        shell: powershell
        run: |
          cd C:\OpenSSL
          Compress-Archive -Path * -DestinationPath openssl-3.5.0-${{ matrix.arch }}-windows-full.zip
          Move-Item openssl-3.5.0-${{ matrix.arch }}-windows-full.zip $env:GITHUB_WORKSPACE\
      - name: Create portable package
        shell: powershell
        run: |
          cd portable-package
          Compress-Archive -Path * -DestinationPath openssl-3.5.0-${{ matrix.arch }}-portable.zip
          Move-Item openssl-3.5.0-${{ matrix.arch }}-portable.zip $env:GITHUB_WORKSPACE\
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openssl-3.5.0-${{ matrix.arch }}-packages
          path: |
            openssl-3.5.0-${{ matrix.arch }}-windows-full.zip
            openssl-3.5.0-${{ matrix.arch }}-portable.zip
          retention-days: 90

  build-macos:
    runs-on: macos-14
    strategy:
      matrix:
        arch: [x64, arm64]
    steps:
      - uses: actions/checkout@v4
      - name: Download and Setup OpenSSL Source
        shell: bash
        run: |
          echo Downloading OpenSSL 3.5.0...
          curl -L -o openssl.zip https://github.com/openssl/openssl/archive/refs/tags/openssl-3.5.0.zip
          echo Extracting archive...
          unzip -q openssl.zip
          mv openssl-openssl-3.5.0 openssl
          echo Verifying directory exists...
          ls -la openssl
      - name: Install Dependencies
        shell: bash
        run: brew install perl
      - name: Configure
        shell: bash
        run: |
          cd openssl
          if [ "${{ matrix.arch }}" = "x64" ]; then
            ./Configure darwin64-x86_64-cc no-shared no-module --prefix=/usr/local/openssl --openssldir=/usr/local/openssl/ssl
          else
            ./Configure darwin64-arm64-cc no-shared no-module --prefix=/usr/local/openssl --openssldir=/usr/local/openssl/ssl
          fi
      - name: Build
        shell: bash
        run: |
          cd openssl
          make
      - name: Install
        shell: bash
        run: |
          cd openssl
          make install
      - name: Create portable executable
        shell: bash
        run: |
          echo Creating portable OpenSSL executable...
          cp /usr/local/openssl/bin/openssl ./openssl
          echo Testing portable executable...
          ./openssl version
          mkdir -p portable-package
          cp ./openssl portable-package/
          echo "OpenSSL 3.5.0 Portable - ${{ matrix.arch }}" > portable-package/README.txt
          echo "=======================================" >> portable-package/README.txt
          echo "" >> portable-package/README.txt
          echo "This is a standalone portable version of OpenSSL 3.5.0" >> portable-package/README.txt
          echo "No installation required - just run the executable." >> portable-package/README.txt
          echo "" >> portable-package/README.txt
          echo "Usage: ./openssl [command] [options]" >> portable-package/README.txt
          echo "" >> portable-package/README.txt
          echo "Examples:" >> portable-package/README.txt
          echo "  ./openssl version" >> portable-package/README.txt
          echo "  ./openssl list -digest-algorithms" >> portable-package/README.txt
          echo "  ./openssl genrsa -out private.key 2048" >> portable-package/README.txt
          echo "  ./openssl req -new -x509 -key private.key -out cert.pem -days 365" >> portable-package/README.txt
          echo "" >> portable-package/README.txt
          echo "Platform: macOS ${{ matrix.arch }}" >> portable-package/README.txt
          echo "Version: OpenSSL 3.5.0" >> portable-package/README.txt
      - name: Package binaries
        shell: bash
        run: |
          cd /usr/local/openssl
          tar -czf openssl-3.5.0-${{ matrix.arch }}-macos-full.tar.gz *
          mv openssl-3.5.0-${{ matrix.arch }}-macos-full.tar.gz $GITHUB_WORKSPACE/
      - name: Create portable package
        shell: bash
        run: |
          cd portable-package
          tar -czf openssl-3.5.0-${{ matrix.arch }}-portable.tar.gz *
          mv openssl-3.5.0-${{ matrix.arch }}-portable.tar.gz $GITHUB_WORKSPACE/
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openssl-3.5.0-${{ matrix.arch }}-packages
          path: |
            openssl-3.5.0-${{ matrix.arch }}-macos-full.tar.gz
            openssl-3.5.0-${{ matrix.arch }}-portable.tar.gz
          retention-days: 90

  build-linux:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        arch: [x64]
    steps:
      - uses: actions/checkout@v4
      - name: Download and Setup OpenSSL Source
        shell: bash
        run: |
          echo Downloading OpenSSL 3.5.0...
          curl -L -o openssl.zip https://github.com/openssl/openssl/archive/refs/tags/openssl-3.5.0.zip
          echo Extracting archive...
          unzip -q openssl.zip
          mv openssl-openssl-3.5.0 openssl
          echo Verifying directory exists...
          ls -la openssl
      - name: Install Dependencies
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential perl
      - name: Configure
        shell: bash
        run: |
          cd openssl
          ./Configure linux-x86_64 no-shared no-module --prefix=/usr/local/openssl --openssldir=/usr/local/openssl/ssl
      - name: Build
        shell: bash
        run: |
          cd openssl
          make
      - name: Install
        shell: bash
        run: |
          cd openssl
          make install
      - name: Create portable executable
        shell: bash
        run: |
          echo Creating portable OpenSSL executable...
          cp /usr/local/openssl/bin/openssl ./openssl
          echo Testing portable executable...
          ./openssl version
          mkdir -p portable-package
          cp ./openssl portable-package/
          echo "OpenSSL 3.5.0 Portable - ${{ matrix.arch }}" > portable-package/README.txt
          echo "=======================================" >> portable-package/README.txt
          echo "" >> portable-package/README.txt
          echo "This is a standalone portable version of OpenSSL 3.5.0" >> portable-package/README.txt
          echo "No installation required - just run the executable." >> portable-package/README.txt
          echo "" >> portable-package/README.txt
          echo "Usage: ./openssl [command] [options]" >> portable-package/README.txt
          echo "" >> portable-package/README.txt
          echo "Examples:" >> portable-package/README.txt
          echo "  ./openssl version" >> portable-package/README.txt
          echo "  ./openssl list -digest-algorithms" >> portable-package/README.txt
          echo "  ./openssl genrsa -out private.key 2048" >> portable-package/README.txt
          echo "  ./openssl req -new -x509 -key private.key -out cert.pem -days 365" >> portable-package/README.txt
          echo "" >> portable-package/README.txt
          echo "Platform: Linux ${{ matrix.arch }}" >> portable-package/README.txt
          echo "Version: OpenSSL 3.5.0" >> portable-package/README.txt
      - name: Package binaries
        shell: bash
        run: |
          cd /usr/local/openssl
          tar -czf openssl-3.5.0-${{ matrix.arch }}-linux-full.tar.gz *
          mv openssl-3.5.0-${{ matrix.arch }}-linux-full.tar.gz $GITHUB_WORKSPACE/
      - name: Create portable package
        shell: bash
        run: |
          cd portable-package
          tar -czf openssl-3.5.0-${{ matrix.arch }}-portable.tar.gz *
          mv openssl-3.5.0-${{ matrix.arch }}-portable.tar.gz $GITHUB_WORKSPACE/
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openssl-3.5.0-${{ matrix.arch }}-packages
          path: |
            openssl-3.5.0-${{ matrix.arch }}-linux-full.tar.gz
            openssl-3.5.0-${{ matrix.arch }}-portable.tar.gz
          retention-days: 90 